remote_theme: daattali/beautiful-jekyll@5.0.0
title: Edwin Tse
description: Everyone says that there is no amount of words could correctly describe him.


###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  About Me: "https://ptse8204.github.io/index.md"
  Projects: "https://ptse8204.github.io/projects.md"
    - Airfare Project: "https://ptse8204.github.io/flightpricebias/"
    - craveforcapes: "https://ptse8204.github.io/craveforcapes"

################
# --- Logo --- #
################

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/icon.jpeg"

# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
round-avatar: true

# If you want to have an image logo in the top-left corner instead of having the title of the website,
# then specify the following parameter
#title-img: /path/to/image
